---
development:
  cloud_name: hztuexfdb
  api_key: '936471212484463'
  api_secret: MkKBL0v_cd2nqfhUww8khbRuuLw
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: hztuexfdb
  api_key: '936471212484463'
  api_secret: MkKBL0v_cd2nqfhUww8khbRuuLw
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: hztuexfdb
  api_key: '936471212484463'
  api_secret: MkKBL0v_cd2nqfhUww8khbRuuLw
  enhance_image_tag: true
  static_image_support: false
